# version: "3.9"
# services:
#   app:
#     build: .
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
# version: '3'

# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: imagica-dev
#     command: bash -c " psql -U postgres && CREATE ROLE admin WITH LOGIN PASSWORD '123456aA;'"
#     volumes:
#       - ./data:/var/lib/postgresql/data

#   web:
#     build: .
#     command: bash -c " python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   api:
#     build: .
#     command: uvicorn contlika.asgi:celestial --host 0.0.0.0 --port 8001
#     volumes:
#       - .:/code
#     ports:
#       - "8001:8001"
#     depends_on:
#       - db

# #   nginx:
# #     image: nginx
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - "80:80"
#     depends_on:
#       - web
#       - api
version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: