version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - "5432:5432"

  web:
    build: .
    env_file:
      - .env.dev
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  api:
    build: .
    volumes:
      - .:/code
    env_file:
      - .env.dev
    command: bash -c "uvicorn contlika.asgi:celestial --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    depends_on:
      - db
