version: '3.8'
services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=imagika
      - POSTGRES_PASSWORD=imagika
      - POSTGRES_DB=imagika_dev
  api:
    build: .
    command: uvicorn contlika.asgi:celestial --host 0.0.0.0 --port 8001
    volumes:
      - ./:/usr/src/app
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  postgres_data: