version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///./app.db"  # Update the database URL
    env_file:
      - .env
