# Generated by Django 4.1.7 on 2023-03-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('strts_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'titles',
                'ordering': ['-strts_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_name', models.CharField(max_length=100)),
                ('interacted', models.TextField(default='{}', null=True)),
                ('myPosts', models.TextField(default='{}', null=True)),
                ('device_id', models.CharField(default='0', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shown_name',
                'verbose_name_plural': 'shown_names',
                'ordering': ['shown_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_name', models.CharField(default=None, max_length=100)),
                ('prompt', models.TextField(default='Create a post.')),
                ('n_prompt', models.TextField(blank=True, null=True)),
                ('uploaded_image', models.UUIDField(default=None, editable=False, null=True)),
                ('generated_image', models.UUIDField(default=None, editable=False, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('publish', models.DateField(null=True)),
                ('like_count', models.IntegerField(default=1)),
                ('dislike_count', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('interacted', models.TextField(default='{}')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='celestial.topic')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='celestial.userprofile')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-publish', 'prompt'],
            },
        ),
        migrations.CreateModel(
            name='MidScoreQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='celestial.post')),
            ],
            options={
                'ordering': ['update_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LowScoreQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='celestial.post')),
            ],
            options={
                'ordering': ['update_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighScoreQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='celestial.post')),
            ],
            options={
                'ordering': ['update_date'],
                'abstract': False,
            },
        ),
    ]
