# Generated by Django 4.1.7 on 2023-03-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-starts_on', 'title'], 'verbose_name': 'title', 'verbose_name_plural': 'titles'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='generated_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='strts_on',
            new_name='starts_on',
        ),
        migrations.AddField(
            model_name='post',
            name='generated_images',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
