# Generated by Django 4.1.7 on 2023-04-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
