# Generated by Django 4.1.7 on 2023-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configs_post_topic_userprofile_delete_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=1),
        ),
    ]
