# Generated by Django 4.1.7 on 2023-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0002_remove_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, default='sample desc', max_length=250, null=True),
        ),
    ]
