# Generated by Django 4.1.7 on 2023-03-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0002_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
