# Generated by Django 4.1.7 on 2023-03-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='intracted',
            new_name='interacted',
        ),
    ]
