# Generated by Django 4.1.7 on 2023-03-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_intracted_userprofile_interacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interacted',
        ),
    ]
