# Generated by Django 4.1.7 on 2023-04-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0004_alter_post_generated_images_alter_post_interacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='interacted',
        ),
        migrations.AddField(
            model_name='post',
            name='interacted',
            field=models.ManyToManyField(to='celestial.userprofile'),
        ),
    ]
