# Generated by Django 4.1.7 on 2023-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0005_remove_post_interacted_post_interacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='myPosts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interacted',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interacted',
            field=models.ManyToManyField(to='celestial.post'),
        ),
    ]
