# Generated by Django 4.1.7 on 2023-03-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_interacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interacted',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
