# Generated by Django 4.1.7 on 2023-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0005_alter_post_options_rename_publish_post_published_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='magic',
            field=models.IntegerField(default=0),
        ),
    ]
