# Generated by Django 4.1.7 on 2023-04-09 16:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0006_remove_userprofile_myposts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='generated_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
        ),
    ]
