# Generated by Django 4.1.7 on 2023-03-11 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_last_gdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_gdt',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 0, 0)),
        ),
    ]
