# Generated by Django 4.1.7 on 2023-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0007_alter_post_generated_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='magic',
            field=models.IntegerField(default=0),
        ),
    ]
