# Generated by Django 4.1.7 on 2023-04-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celestial', '0008_userprofile_magic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
