# Generated by Django 4.1.7 on 2023-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_device_id_alter_userprofile_interacted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='shown_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
