# Generated by Django 4.1.7 on 2023-03-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
