# Generated by Django 4.1.7 on 2023-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_post_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='myPosts',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
