# Generated by Django 4.1.7 on 2023-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_myposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_gdt',
        ),
        migrations.AddField(
            model_name='post',
            name='interacted',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interacted',
            field=models.TextField(default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='myPosts',
            field=models.TextField(default='{}', null=True),
        ),
    ]
