# Generated by Django 4.1.7 on 2023-03-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_userprofile_last_gdt_post_interacted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highscorequeue',
            options={'ordering': ['update_date']},
        ),
        migrations.AlterModelOptions(
            name='lowscorequeue',
            options={'ordering': ['update_date']},
        ),
        migrations.AlterModelOptions(
            name='midscorequeue',
            options={'ordering': ['update_date']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-strts_on', 'title'], 'verbose_name': 'title', 'verbose_name_plural': 'titles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['shown_name'], 'verbose_name': 'shown_name', 'verbose_name_plural': 'shown_names'},
        ),
        migrations.AlterField(
            model_name='highscorequeue',
            name='id',
            field=models.CharField(default='0', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='highscorequeue',
            name='post',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='celestial.post'),
        ),
        migrations.AlterField(
            model_name='lowscorequeue',
            name='id',
            field=models.CharField(default='0', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lowscorequeue',
            name='post',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='celestial.post'),
        ),
        migrations.AlterField(
            model_name='midscorequeue',
            name='id',
            field=models.CharField(default='0', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='midscorequeue',
            name='post',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='celestial.post'),
        ),
    ]
