# Generated by Django 4.1.7 on 2023-03-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_highscorequeue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscorequeue',
            name='id',
            field=models.IntegerField(default=0, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lowscorequeue',
            name='id',
            field=models.IntegerField(default=0, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='midscorequeue',
            name='id',
            field=models.IntegerField(default=0, max_length=8, primary_key=True, serialize=False),
        ),
    ]
